#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Status dos mercados para os controles operacionais.

Safe-by-default: statuses other than ATIVA are treated as blocked for any
operational decision. This module does not unlock betting; it only exposes
read-only lifecycle state generated by the simulation/audit engine.
"""
from __future__ import annotations

from pathlib import Path
from typing import Any, Dict, Tuple

from core.project_paths import REPORTS_DIR, read_json

STATUS_MERCADOS_PATH = REPORTS_DIR / "status_mercados.json"
MARKET_LIFECYCLE_PATH = REPORTS_DIR / "ciclo_vida_mercados.json"
PERFIL_OPERACIONAL_PATH = REPORTS_DIR / "perfil_operacional_mercados.json"

ATIVA = "ATIVA"
OBSERVACAO = "OBSERVACAO"
APOSENTADA = "APOSENTADA"
BLOQUEADA = "BLOQUEADA"
DESCONHECIDA = "DESCONHECIDA"

BLOCKING_STATUSES = {OBSERVACAO, APOSENTADA, BLOQUEADA, DESCONHECIDA}


def load_mercado_lifecycle_state() -> Dict[str, Any]:
    """Carrega o status oficial dos mercados.

    Ordem:
    1. status_mercados.json
    2. ciclo_vida_mercados.json
    3. perfil_operacional_mercados.json
    """

    data = read_json(STATUS_MERCADOS_PATH, {})
    if isinstance(data, dict) and data.get("mercados"):
        return data

    data = read_json(MARKET_LIFECYCLE_PATH, {})
    if isinstance(data, dict) and data.get("mercados"):
        return data

    perfil = read_json(PERFIL_OPERACIONAL_PATH, {})
    if isinstance(perfil, dict) and perfil:
        mercados = {}

        for mercado, info in perfil.items():
            if not isinstance(info, dict):
                continue

            ativo = info.get("ativo") is True

            mercados[str(mercado)] = {
                "status_ciclo_vida": ATIVA if ativo else BLOQUEADA,
                "motivo": (
                    "PERFIL_OPERACIONAL_ATIVO"
                    if ativo
                    else info.get("motivo") or "PERFIL_OPERACIONAL_INATIVO"
                ),
                "acao_recomendada": (
                    "OPERAR_COM_GUARDS"
                    if ativo
                    else "NAO_OPERAR"
                ),
                **info,
            }

        return {
            "fonte": "perfil_operacional_mercados",
            "mercados": mercados,
        }

    return {}


def get_mercado_lifecycle(mercado: str) -> Dict[str, Any]:
    state = load_mercado_lifecycle_state()
    mercados = state.get("mercados", {}) if isinstance(state, dict) else {}
    info = mercados.get(str(mercado), {}) if isinstance(mercados, dict) else {}
    if not isinstance(info, dict):
        info = {}
    status = str(info.get("status_ciclo_vida") or DESCONHECIDA).upper()
    if status not in {ATIVA, OBSERVACAO, APOSENTADA, BLOQUEADA, DESCONHECIDA}:
        status = DESCONHECIDA
    return {
        "mercado": str(mercado),
        "status_ciclo_vida": status,
        "motivo": info.get("motivo") or "STATUS_MERCADO_NAO_ENCONTRADO",
        "acao_recomendada": info.get("acao_recomendada"),
        **info,
    }


def is_mercado_allowed_by_lifecycle(mercado: str) -> Tuple[bool, str, str]:
    info = get_mercado_lifecycle(mercado)
    status = str(info.get("status_ciclo_vida") or DESCONHECIDA).upper()
    motivo = str(info.get("motivo") or "STATUS_MERCADO_NAO_ENCONTRADO")
    if status == ATIVA:
        return True, ATIVA, "ok"
    if status == APOSENTADA:
        return False, APOSENTADA, "MERCADO_APOSENTADO"
    if status == OBSERVACAO:
        return False, OBSERVACAO, "MERCADO_EM_OBSERVACAO"
    if status == BLOQUEADA:
        return False, BLOQUEADA, "MERCADO_BLOQUEADO"
    return False, DESCONHECIDA, "MERCADO_DESCONHECIDO"


def lifecycle_summary() -> Dict[str, int]:
    state = load_mercado_lifecycle_state()
    mercados = state.get("mercados", {}) if isinstance(state, dict) else {}
    out = {"active": 0, "watchlist": 0, "retired": 0, "blocked": 0, "unknown": 0}
    if not isinstance(mercados, dict):
        return out
    for info in mercados.values():
        status = str((info or {}).get("status_ciclo_vida") or DESCONHECIDA).upper()
        if status == ATIVA:
            out["active"] += 1
        elif status == OBSERVACAO:
            out["watchlist"] += 1
        elif status == APOSENTADA:
            out["retired"] += 1
        elif status == BLOQUEADA:
            out["blocked"] += 1
        else:
            out["unknown"] += 1
    return out
